In [14]:
# Here are the sample documents combining together to form a corpus.

doc1 = "Sugar is bad to consume. My sister likes to have sugar, but not my father. bad"

doc2 = "My father spends a lot of time driving my sister around to dance practice. sister driving driving"

doc3 = "Doctors suggest that driving may cause increased stress and blood pressure. Doctors stress"

doc4 = "Sometimes I feel pressure to perform well at school, but my father never seems to drive my sister to do better. pressure"

doc5 = "Health experts say that Sugar is not good for your lifestyle. Health lifestyle"

In [15]:
# compile documents

doc_list = [doc1, doc2, doc3, doc4, doc5]
doc_list

['Sugar is bad to consume. My sister likes to have sugar, but not my father. bad',
 'My father spends a lot of time driving my sister around to dance practice. sister driving driving',
 'Doctors suggest that driving may cause increased stress and blood pressure. Doctors stress',
 'Sometimes I feel pressure to perform well at school, but my father never seems to drive my sister to do better. pressure',
 'Health experts say that Sugar is not good for your lifestyle. Health lifestyle']

In [16]:
type(doc_list)

list

In [17]:
# List to Dataframe
import pandas as pd
df = pd.DataFrame(doc_list, columns =['text']) 
df

                                                text
0  Sugar is bad to consume. My sister likes to ha...
1  My father spends a lot of time driving my sist...
2  Doctors suggest that driving may cause increas...
3  Sometimes I feel pressure to perform well at s...
4  Health experts say that Sugar is not good for ...

In [18]:
# Import CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(stop_words='english')

# Create Document Term Matrix
dtm_csr = cv.fit_transform(df['text'])

In [19]:
dtm_df = pd.DataFrame(dtm_csr.toarray(), columns=cv.get_feature_names())
dtm_df.index = df.index
dtm_df.head()

,bad,better,blood,cause,consume,dance,doctors,drive,driving,experts,...,practice,pressure,say,school,sister,spends,stress,sugar,suggest,time
0,2,0,0,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,2,0,0
1,0,0,0,0,0,1,0,0,3,0,...,1,0,0,0,2,1,0,0,0,1
2,0,0,1,1,0,0,2,0,1,0,...,0,1,0,0,0,0,2,0,1,0
3,0,1,0,0,0,0,0,1,0,0,...,0,2,0,1,1,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,1,...,0,0,1,0,0,0,0,1,0,0